# Generated by Django 6.0 on 2026-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
